server:
  port: 8081
dubbo:
  protocol:
    name: dubbo
    port: 20882
  registry:
    address: spring-cloud://192.168.10.8
  cloud:
    subscribed-services: dubbo-spring-cloud-provider
spring:
  application:
    name: dubbo-spring-cloud-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.8:8848
  main:
    allow-bean-definition-overriding: true





