server:
  port: 8000
dubbo:
  scan:
    base-packages: com.cloud.mall.service
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: spring-cloud://127.0.0.1:8848
spring:
  application:
    name: dubbo-spring-cloud-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: Yy@5021067813
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  main:
    allow-bean-definition-overriding: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cloud.mall.model #所有entity别名所在包